export const WINDOW_RESIZED = "WINDOW_RESIZED";
export const MOUSE_DOWN = "MOUSE_PRESSED";
export const MOUSE_CLICK = "MOUSE_CLICKED";
export const MOUSE_UP = "MOUSE_RELEASED";
export const MOUSE_MOVE = "MOUSE_MOVED";
export const MOUSE_OVER = "MOUSE_OVER";
export const MOUSE_OUT = "MOUSE_OUT";
export const MOUSE_WHEEL = "MOUSE_WHEEL";
export const ADD_LINK = "LINK_ADDED";
export const ADD_MUSIC = "MUSIC_ADDED";
export const ADD_MUSICS = "ADD_MUSICS";
export const PLAYER_PLAYING = "PLAYER_PLAYING";
export const PLAYER_MUTED = "PLAYER_MUTED";
export const PLAYER_PREVIOUS = "PLAYER_PREVIOUS";
export const PLAYER_NEXT = "PLAYER_NEXT";
export const SET_VOLUME = "SET_VOLUME";
export const PLAYER_SHUFFLE = "PLAYER_SHUFFLE";
export const SET_TIME = "SET_TIME";
export const SET_REQUESTED_TIME = "SET_REQUESTED_TIME";
export const CURRENT_REGION = "CURRENT_REGION";
export const CURRENT_GENRE = "CURRENT_GENRE";
export const TOGGLE_MUSIC_GENRE_SELECTED = "TOGGLE_MUSIC_GENRE_SELECTED";
export const TOGGLE_MUSIC_REGION_SELECTED = "TOGGLE_MUSIC_REGION_SELECTED";
export const SET_CONNECTION_TOKEN = "SET_CONNECTION_TOKEN";
export const ADD_REGIONS = "ADD_REGIONS";
export const ADD_GENRES = "ADD_GENRES";
export const SET_REQUEST_STATE_MUSIC_GENRES = "SET_REQUEST_STATE_MUSIC_GENRES";

export default [
  WINDOW_RESIZED,
  MOUSE_DOWN,
  MOUSE_CLICK,
  MOUSE_UP,
  MOUSE_MOVE,
  MOUSE_OVER,
  MOUSE_OUT,
  MOUSE_WHEEL,
  ADD_LINK,
  ADD_MUSIC,
  ADD_MUSICS,
  PLAYER_PLAYING,
  PLAYER_MUTED,
  PLAYER_PREVIOUS,
  PLAYER_NEXT,
  SET_VOLUME,
  PLAYER_SHUFFLE,
  SET_TIME,
  SET_REQUESTED_TIME,
  CURRENT_REGION,
  CURRENT_GENRE,
  TOGGLE_MUSIC_GENRE_SELECTED,
  TOGGLE_MUSIC_REGION_SELECTED,
  SET_CONNECTION_TOKEN,
  ADD_REGIONS,
  ADD_GENRES,
  SET_REQUEST_STATE_MUSIC_GENRES
];
